version: "3"

env:
  NODE_ENV: development

tasks:
  # ========================================
  # MAIN DEVELOPMENT TASKS
  # ========================================

  default:
    desc: Show available tasks
    cmd: task --list

  install:
    desc: Install all dependencies for both app and convex
    cmds:
      - echo "ðŸ“¦ Installing Convex dependencies..."
      - task: install:convex
      - echo "ðŸ“¦ Installing App dependencies..."
      - task: install:app
      - echo "âœ… All dependencies installed!"

  install:convex:
    internal: true
    dir: convex
    cmd: pnpm install

  install:app:
    internal: true
    dir: app
    cmd: yarn install

  dev:
    desc: Start development environment (convex + app)
    deps: [install]
    cmds:
      - echo "ðŸš€ Starting development environment..."
      - echo "ðŸ”§ Starting Convex development server..."
      - |
        cd convex && pnpm dev &
        sleep 5
      - echo "ðŸ”„ Syncing API types..."
      - task: convex:sync-api
      - echo "ðŸ“± Starting mobile app..."
      - echo "ðŸ”— Convex - http://localhost:3000"
      - echo "ðŸ“± Expo - http://localhost:8081"
      - echo "âš ï¸  Keep this terminal open for both services"
      - task: app:dev

  build:
    desc: Build the entire project
    cmds:
      - echo "ðŸ—ï¸ Building project..."
      - task: convex:build
      - task: app:build
      - echo "âœ… Build complete!"

  # ========================================
  # CONVEX BACKEND TASKS
  # ========================================

  convex:dev:
    desc: Start Convex development server
    dir: convex
    cmd: pnpm dev

  convex:deploy:
    desc: Deploy Convex to production
    dir: convex
    cmd: pnpm deploy

  convex:build:
    desc: Build Convex backend
    dir: convex
    cmd: echo "âœ… Convex builds automatically on deploy"

  convex:test:
    desc: Run Convex tests
    dir: convex
    cmd: pnpm test

  convex:test:watch:
    desc: Run Convex tests in watch mode
    dir: convex
    cmd: pnpm test -- --watch

  convex:sync-api:
    desc: Generate and sync API types to frontend
    dir: convex
    cmd: pnpm sync-api

  convex:login:
    desc: Login to Convex (required for first-time setup)
    dir: convex
    cmd: npx convex login

  convex:configure:
    desc: Configure Convex project (creates convex.json without starting dev server)
    dir: convex
    cmd: npx convex dev --configure --once

  convex:stop:
    desc: Stop Convex development server
    cmd: |
      pkill -f "convex/bin/main.js dev" || echo "No Convex dev server running"

  # ========================================
  # MOBILE APP TASKS
  # ========================================

  app:dev:
    desc: Start Expo development server
    dir: app
    cmd: yarn start

  app:ios:
    desc: Run app on iOS simulator
    dir: app
    cmd: yarn ios

  app:android:
    desc: Run app on Android emulator
    dir: app
    cmd: yarn android

  app:web:
    desc: Run app in web browser
    dir: app
    cmd: yarn web

  app:build:
    desc: Build mobile app
    dir: app
    cmd: npx expo export

  app:test:
    desc: Run mobile app tests
    dir: app
    cmd: yarn test

  # ========================================
  # SETUP & MAINTENANCE TASKS
  # ========================================

  init:
    desc: Initialize project with dependencies and Convex configuration
    cmds:
      - echo "ðŸš€ Initializing Fullstack Template project..."
      - task: install
      - echo "ðŸ” Setting up Convex backend..."
      - task: convex:login
      - task: convex:configure
      - echo "ðŸ”„ Syncing API types..."
      - task: convex:sync-api
      - echo "âš™ï¸ Setting up environment file..."
      - cp .env.example app/.env.local
      - |
        if [ -f convex/.env.local ]; then
          CONVEX_URL=$(grep CONVEX_URL convex/.env.local | cut -d '=' -f2)
          if [ ! -z "$CONVEX_URL" ]; then
            sed -i.bak "s|EXPO_PUBLIC_CONVEX_URL=.*|EXPO_PUBLIC_CONVEX_URL=$CONVEX_URL|" app/.env.local && rm app/.env.local.bak
            echo "âœ… Automatically configured EXPO_PUBLIC_CONVEX_URL=$CONVEX_URL in app/.env.local"
          else
            echo "âš ï¸ Could not extract Convex URL. Please update app/.env.local manually."
          fi
        else
          echo "âš ï¸ Convex .env.local not found. Please update app/.env.local manually."
        fi
      - echo "âœ… Initialization complete!"
      - echo "ðŸ“ Next steps:"
      - echo "   1. Verify EXPO_PUBLIC_CONVEX_URL in app/.env.local"
      - echo "   2. Run - task dev to start development"

  clean:
    desc: Clean all build artifacts and dependencies
    cmds:
      - echo "ðŸ§¹ Cleaning project..."
      - rm -rf app/node_modules app/.expo app/dist
      - rm -rf convex/node_modules convex/_generated
      - echo "âœ… Clean complete!"

  reset:
    desc: Reset project (clean + install)
    cmds:
      - task: clean
      - task: install

  # ========================================
  # TESTING TASKS
  # ========================================

  test:
    desc: Run all tests
    cmds:
      - echo "ðŸ§ª Running all tests..."
      - task: convex:test
      - task: app:test
      - echo "âœ… All tests complete!"

  test:watch:
    desc: Run tests in watch mode
    cmds:
      - task: convex:test:watch &
      - task: app:test

  # ========================================
  # LINTING & FORMATTING
  # ========================================

  lint:
    desc: Lint all code
    cmds:
      - echo "ðŸ” Linting code..."
      - task: lint:app
      - task: lint:convex

  lint:app:
    internal: true
    dir: app
    cmd: yarn lint || echo "âš ï¸ App linting not configured"

  lint:convex:
    internal: true
    dir: convex
    cmd: pnpm lint || echo "âš ï¸ Convex linting not configured"

  format:
    desc: Format all code
    cmds:
      - echo "âœ¨ Formatting code..."
      - task: format:app
      - task: format:convex

  format:app:
    internal: true
    dir: app
    cmd: yarn format || echo "âš ï¸ App formatting not configured"

  format:convex:
    internal: true
    dir: convex
    cmd: pnpm format || echo "âš ï¸ Convex formatting not configured"

  # ========================================
  # DOCUMENTATION TASKS
  # ========================================

  docs:
    desc: Open documentation
    cmd: echo "ðŸ“š See README.md and docs/ folder for comprehensive documentation"

  # ========================================
  # UTILITY TASKS
  # ========================================

  status:
    desc: Show project status
    cmds:
      - echo "ðŸ“‹ Project Status:"
      - echo "Backend{{":"}} Convex"
      - echo "Frontend{{":"}} React Native + Expo"
      - echo "UI{{":"}} Tamagui"
      - task: status:convex
      - task: status:app

  status:convex:
    internal: true
    dir: convex
    cmd: |
      echo "Convex dependencies:" && pnpm list --depth=0 2>/dev/null | head -10 || echo "Run 'task install' first"

  status:app:
    internal: true
    dir: app
    cmd: |
      echo "App dependencies:" && yarn list --depth=0 2>/dev/null | head -10 || echo "Run 'task install' first"
